### ISSUE TITLE
Parallel compilation with GNU Make doesn't work

### ISSUE THREAD

**Issue by qeeg** [dirkwhoffmann/vAmigaBM#2]
Running something like `make -j12` will just fallback to `-j1` for the whole compilation, thus slowing down compile times.

**Comment by dirkwhoffmann** [comment]
This is strange. According to the docs, the -j option is propagated down to all recursively called make instances. In fact it does work that way on macOS (it compiles in parallel on my dev machine). In my Linux VM, it doesn't seem to parallelise anything. On which platform did you compile the app?

**Comment by qeeg** [comment]
Arch Linux

**Comment by amiga23** [comment]
There is a warning message:
```
$ make -j 4
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
```

**Comment by dirkwhoffmann** [comment]
https://stackoverflow.com/questions/24818095/warning-forced-in-submake-in-parallel-execution-of-make
> "Usually this message occurres if you call make from your Makefile not by the variable $(MAKE)"

My Makefiles were using a customised macro called `$(MYMAKE)` instead of `$(MAKE)`. I've changed that, and with some luck the error is gone. I cannot test it on my machine (macOS), because it worked with the old version, too.

**Comment by amiga23** [comment]
I can confirm that it works fine now. :+1:
